<ul class="form-select__list">
    <li class="form-select__list-item">Betriebswirtschaftslehre (BWL)</li>
    <li class="form-select__list-item">Allgemeine Volkswirtschaft</li>
    <li class="form-select__list-item">Management</li>
    <li class="form-select__list-item">Sportökonomie</li>
    <li class="form-select__list-item">Wirtschaftspsychologie</li>
    <li class="form-select__list-item">Wirtschaftsingenieurwesen</li>
    <li class="form-select__list-item">Marketing</li>
    <li class="form-select__list-item">Rechtsgeschichte</li>
    <li class="form-select__list-item">Handelsrecht</li>
    <li class="form-select__list-item">Strafrecht</li>
    <li class="form-select__list-item">Arbeitsrecht</li>
    <li class="form-select__list-item">Steuerrecht</li>
    <li class="form-select__list-item">Familienrecht</li>
    <li class="form-select__list-item">Wirtschaftsrecht</li>
    <li class="form-select__list-item">Herkunft von Sprachen</li>
    <li class="form-select__list-item">Entwicklung von Sprachen</li>
    <li class="form-select__list-item">Bestandteile von Sprachen</li>
    <li class="form-select__list-item">Einheiten von Sprachen</li>
    <li class="form-select__list-item">Kommunikation, Wahrnehmung</li>
    <li class="form-select__list-item">Semantik</li>
    <li class="form-select__list-item">Sprachvergleich, Sprachsysteme</li>
    <li class="form-select__list-item">Dialektologie</li>
    <li class="form-select__list-item">Lexikologie</li>
    <li class="form-select__list-item">Linguistik des Textes</li>
    <li class="form-select__list-item">Literaturwissenschaft</li>
    <li class="form-select__list-item">Bibliothekswissenschaft</li>
    <li class="form-select__list-item">Soziolinguistik</li>
    <li class="form-select__list-item">Philologie</li>
    <li class="form-select__list-item">Politische Institutionen</li>
    <li class="form-select__list-item">Sprachwissenschaft</li>
    <li class="form-select__list-item">Pharmazie</li>
    <li class="form-select__list-item">Anatomie</li>
    <li class="form-select__list-item">Anästhesiologie</li>
    <li class="form-select__list-item">Chirurgie</li>
    <li class="form-select__list-item">Gesundheitswissenschaft</li>
    <li class="form-select__list-item">Humanmedizin</li>
    <li class="form-select__list-item">Kinder- und Jugendmedizin</li>
    <li class="form-select__list-item">Hygiene- und Umweltmedizin</li>
    <li class="form-select__list-item">Neurologie</li>
    <li class="form-select__list-item">Pathologie</li>
    <li class="form-select__list-item">Gesundheitsmanagement</li>
    <li class="form-select__list-item">Physiologie</li>
    <li class="form-select__list-item">Pflegewissenschaften</li>
    <li class="form-select__list-item">Orthopädie</li>
    <li class="form-select__list-item">Vorschul-Pädagogik</li>
    <li class="form-select__list-item">Geschichte der Pädagogik</li>
    <li class="form-select__list-item">Logopädie</li>
    <li class="form-select__list-item">Methodik des Unterrichts</li>
    <li class="form-select__list-item">Pädagogische Innovation</li>
    <li class="form-select__list-item">Sozialpädagogik</li>
    <li class="form-select__list-item">Sonderpädagogik</li>
    <li class="form-select__list-item">Vergleichende Pädagogik</li>
    <li class="form-select__list-item">Taubstummenpädagogik</li>
    <li class="form-select__list-item">Erziehungstheorie</li>
    <li class="form-select__list-item">Schulbildung</li>
    <li class="form-select__list-item">Blindenpädagogik</li>
    <li class="form-select__list-item">Sehbehindertenpädagogik</li>
    <li class="form-select__list-item">Didaktik</li>
    <li class="form-select__list-item">Andere</li>
</ul>